# Generated by Django 5.2.6 on 2025-09-23 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='registration_limit',
            new_name='max_participants',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='registration_end_time',
            new_name='registration_deadline',
        ),
    ]
