# Generated by Django 5.2.6 on 2025-09-23 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_registration_limit_event_max_participants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='my_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
