# Generated by Django 5.2.5 on 2025-09-16 06:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_event_end_time_event_meeting_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userotp',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='owners',
            field=models.ManyToManyField(related_name='event_owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userotp',
            name='owners',
            field=models.ManyToManyField(related_name='userotp_owners', to=settings.AUTH_USER_MODEL),
        ),
    ]
