# Generated by Django 5.2.6 on 2025-09-17 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_event_user_remove_userotp_user_event_owners_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='owners',
            field=models.ManyToManyField(related_name='owned_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
