# Generated by Django 5.2.6 on 2025-09-17 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_event_owners'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_admin_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owned_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
